language: python
dist: bionic

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  global:
    - SAMTOOLS_VER=1.3.1
  jobs:
    - R_VER=3.3.2 GGPLOT_VER=2.2.1

install:
  - sudo apt update
  # Better to have same version as the env python
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge

  # For debugging
  - conda info -a

  - conda create -q -n test-env samtools=$SAMTOOLS_VER r-base=$R_VER r-ggplot2=$GGPLOT_VER r-gridextra r-data.table r-svglite
  - conda activate test-env
  - pip install tox-travis pysam

script:
  - tox
  - source .tox/$TOXENV/bin/activate && bash ci/run.sh
