FROM debian:stable

LABEL maintainer "Emilio Palumbo <emilio.palumbo@crg.eu>" \
      version "1.0" \
      description "Docker image for ggsashimi"

# install needed tools
RUN apt-get update --fix-missing -qq && \
        apt-get install -y -q \
    locales \
    r-base \
    python \
    python-pip \
    libcairo2-dev \
    && apt-get clean \
    && apt-get purge \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# set locale
RUN sed -i '/en_US.UTF-8/ s/^#\s\+//' /etc/locale.gen && \
    locale-gen
ENV LANG=en_US.UTF-8

# Install pysam
RUN pip install pysam

# Install R packages for ggplot2
RUN R -e 'install.packages( c("ggplot2", "gridExtra", "data.table", "svglite"), repos="http://cloud.r-project.org/");'

# Copy ggsashimi in the docker image
ADD sashimi-plot.py /

# Run the container as an executable
ENTRYPOINT ["/sashimi-plot.py"]

